name: hsic_align
channels:
- defaults
- conda-forge
dependencies:
- python=3.8
# Standard Libraries
- numpy             # Numerical Linear Algebra
- scipy             # Scientific Computing
- pandas            # Data structure
- scikit-learn      # Machine Learning
# Plotting Libraries
- matplotlib        # standard plotting library
- seaborn           # Stats viz library
# GUI
- ipykernel         # Be seen in other jupyterlabs
- nodejs            # for extensions in jupyterlab
- tqdm              # Progress bars
- ipywidgets #
# Testing
- pytest            # Modern Testing
# Formatter
- black             # Uncompromising formatter
- isort             # sorts packages
- flake8
- pylint
# Gaussian Processes
- pip
- pip:
  - joblib          # Embarssingly parallel